---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyber_root_music
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cyber_root_music
  template:
    metadata:
      labels:
        app: cyber_root_music
    spec:
      containers:
        - name: cyber_root_music
          image: "ghcr.io/nekko-lab/cyber_root_music-app:SHA"
---
apiVersion: v1
kind: Service
metadata:
  name: cyber_root_music-svc
spec:
  selector:
    app: cyber_root_music
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
