apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "ghcr.io/nekko-lab/tsudanuma24-hp:967976212cde4d6be9e9443548ba41ca15097b1d"
