apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "ghcr.io/nekko-lab/tsudanuma24-hp:e1208e7dba7ef47ac37a377ea2b58cd1e09bb6fb"
